kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-service
    spec:
      selector:
        matchLabels:
        app: kafka-service
      template:
        metadata:
          labels:
          app: kafka-service
          spec:
          replicas: 1
          containers:

            – name: kafka-service
            image: wurstmeister/kafka
          ports:
            – containerPort: 9092
          env:
            – name: KAFKA_LISTENERS
            value: INTERNAL://:32323,EXTERNAL://:9092
            – name: KAFKA_ADVERTISED_LISTENERS
            value: INTERNAL://kafka-service:32323,EXTERNAL://10.152.183.230:9092
            – name: KAFKA_ZOOKEEPER_CONNECT
            value: 10.152.183.182:2181
            – name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            – name: KAFKA_CREATE_TOPICS
            value: ceyark-test:1:1
            – name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: INTERNAL
